name: flutter_loggin
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  flutter_swiper_null_safety: ^1.0.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  intl: ^0.20.1
  google_sign_in: ^6.0.1
  shared_preferences: ^2.3.5
  firebase_core: ^3.10.1 # Necesario para inicializar Firebase
  firebase_auth: ^5.4.1 # Para autenticación (opcional)
  firebase_app_check: ^0.3.0+1 # Para App Check
  cloud_firestore: ^5.3.1 # Para Firestore (opcional)
  firebase_storage: ^12.4.1 # Para almacenamiento de archivos (opcional)
  dio: ^5.4.0
  flame: ^1.24.0
  flame_audio: ^2.10.8
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/galeriaPlantes/
    - assets/
    - assets/fonts/
    - assets/fondoBatalla.jpg
    - assets/images/player.png
    - assets/images/enemy.png
  fonts:
    - family: RiverAdventurer
      fonts:
        - asset: assets/fonts/RiverAdventurer.ttf